#include "macros.asm"
#include "charmap.asm"

#include "hram.asm"
#include "vram.asm"

#include "constants/hardware_constants.asm"
#include "constants/oam_constants.asm"
#include "constants/misc_constants.asm"

#include "constants/pokemon_constants.asm"
#include "constants/pokedex_constants.asm"
#include "constants/trainer_constants.asm"
#include "constants/item_constants.asm"
#include "constants/type_constants.asm"
#include "constants/move_constants.asm"
#include "constants/move_animation_constants.asm"
#include "constants/move_effect_constants.asm"
#include "constants/status_constants.asm"
#include "constants/sprite_constants.asm"
#include "constants/palette_constants.asm"
#include "constants/evolution_constants.asm"
#include "constants/list_constants.asm"
#include "constants/map_constants.asm"
#include "constants/connection_constants.asm"
#include "constants/hide_show_constants.asm"
#include "constants/credits_constants.asm"
#include "constants/music_constants.asm"
#include "constants/tilesets.asm"
#include "constants/starter_mons.asm"
#include "constants/event_constants.asm"
#include "constants/text_constants.asm"
